/*
 * Copyright (c) 2024 naskio (Original Author)
 * Copyright (c) 2025 Sergei Trufanov (Fork Author)
 * 
 * This file has been modified from the original n8n-nodes-python project.
 * Original project: https://github.com/naskio/n8n-nodes-python
 * 
 * Licensed under the Apache License, Version 2.0 with Commons Clause.
 * See LICENSE.md file for details.
 * 
 * 🚨 CRITICAL WARNING: 100% OF MODIFICATIONS GENERATED BY AI 🚨
 * ALL modifications and new features (100%) were developed with AI assistance.
 * This code may contain CRITICAL ERRORS, security vulnerabilities, or
 * unexpected behavior. USE AT YOUR OWN RISK. Thorough testing required.
 * 
 * This software is provided for personal, non-commercial use only.
 * The maintainer assumes no responsibility for any use by third parties.
 */

import {
	ICredentialType,
	INodeProperties,
} from 'n8n-workflow';


export class PythonEnvVars implements ICredentialType {
	displayName = 'Python Environment Variables';
	name = 'pythonEnvVars';
	properties: INodeProperties[] = [
		{
			displayName: '.env File Content',
			name: 'envFileContent',
			typeOptions: {
				rows: 10,
			},
			type: 'string',
			default: '',
			placeholder: 'HELLO=World!\n',
			description: 'The content of the .env file.',
		},
		// {
		// 	displayName: 'Environment Variables',
		// 	name: 'envVars',
		// 	type: 'fixedCollection',
		// 	// type: 'collection',
		// 	// type: 'string',
		// 	default: {},
		// 	placeholder: 'Add environment variable',
		// 	typeOptions: {
		// 		multipleValues: true,
		// 		sortable: true,
		// 	},
		// 	description: 'Environment variables.',
		// 	options: [
		// 		{
		// 			name: 'envVar',
		// 			displayName: 'Environment Variable',
		// 			values: [
		// 				{
		// 					displayName: 'Name',
		// 					name: 'name',
		// 					type: 'string',
		// 					default: '',
		// 					description: 'Name of the environment variable.',
		// 				},
		// 				{
		// 					displayName: 'Value',
		// 					name: 'value',
		// 					type: 'string',
		// 					default: '',
		// 					description: 'Value of the environment variable.',
		// 					typeOptions: {
		// 						password: true,
		// 					},
		// 				},
		// 			],
		// 		},
		// 	],
		// },
	];
}
